parameters:
services:
    app.age.calculator:
        class: App\AgeCalculator\AgeCalculator
       
    app.age.calculator.manager:
        class: App\AgeCalculator\AgeCalculatorManager
        arguments:
            $ageCalculator: '@app.age.calculator'
            
    app:age:calculator:
        class: App\Command\AgeCalculatorCommand
        arguments:
            $ageCalculatorManager: '@app.age.calculator.manager'